language: 'node_js'
node_js:
  - '6.12.0'

install:
  - npm install

before_script:
  - npm run test

script:
  - npm run build:prod

deploy:
  api_key:
    secure: iZJspGVIlHz23PrP27hT6BTeFvph7CIkUl3a9yFmDsOqSqvvMZ9QYdhCQeuuYEFAb51LGGTQTUP8g/wYtU39tE+W1EI9mCnW+AaPSO5lIqlEgyzugTI7OBLZw7BwX95CHXbUI6EUP6xCQbfWYON95gxqZOlphtbXCm00kZGVpJ7XcK5dZ7sYy09WPsLy8adHiBerpx70hbfkRv9UxgC94UtRt3WO7pHCpnIvQakjf2faULcbi2KizniR7IxW/z/T4O4ER2xsJDPzRUSeY4BlfheLaWOOmKw/KUzOvn349yTovYb7AWE33Y97bzLLPAea/+VB+Lyd3n1ipZZkkz2+GlCZl8fMLDazHa/BUCt3pdrGJtVX+NOP8GNz8hPJo/ttK9Kd+tpCd/GW8rf46E5GUnu4ojSfPEZSJdzDb4g0wD1vkksEz13lIy1qVm51ZzEkrA2TOJmVx60BX/w3GQC+k56axTJ3UFa6XoSCkVZGIZaAy44ykiGY2ht0tO18OLfN5TT8X72/45xIYX6CKhwlUG5JFkDStR7NveiuD81Tz9C61pFbJXkmW0ArQ5ZfuDGy9vfAUg+3p05IzCsv4Rq7OOcJMVUwNf2LfulvjzFANL4otSL6eXnIB/cDICIiBy84WX6PvESBjH7r1HKENDuRO04XWRMwfk9ePnDeSBMCtYI=
